Script started on 2023-11-29 01:29:25-05:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="167" LINES="11"]
]0;ajm94@remotel1: ~/CS374/Homework04[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04[00m$ cd original/
]0;ajm94@remotel1: ~/CS374/Homework04/original[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/original[00m$ cat squareAndSum.c
/* squareAndSum.c computes the sum of the squares
 *  of the values in an input file,
 *  whose name is given on the command-line.
 *
 * The program is written using typedef to declare
 *  Item as a generic type, currently double.
 *
 * Joel Adams, Fall 2023
 * for CS 374 (HPC) at Calvin University.
 * 
 * Alex Miller
 * Calvin University
 * 6 Dec 2023
 * 
 */

#include <stdio.h>      /* I/O */
#include <stdlib.h>     /* calloc(), exit(), etc. */
#include <mpi.h>

typedef double Item;

void readArray(char * fileName, Item ** a, int * n);
double arraySquareAndSum(Item* a, int numValues);

int main(int argc, char * argv[])
{
  MPI_Init(&argc, &argv);
  double start_time = MPI_Wtime();
  int  howMany;
  Item sum;
  Item* a;

  if (argc != 2) {
    fprintf(stderr, "\n*** Usage: squareAndSum <inputFile>\n\n");
    exit(1);
  }
  
  readArray(argv[1], &a, &howMany);
  double afterArrTime = MPI_Wtime() - start_time;
  double sum_start = MPI_Wtime();
  sum = arraySquareAndSum(a, howMany);
  double sumTime = MPI_Wtime() - sum_start;
  printf("The sum of the squares of the values in the file '%s' is %g\nTimes: %f, %f, %f\n", argv[1], sum, afterArrTime, sumTime, afterArrTime + sumTime);

  free(a);

  return 0;
}

/* readArray fills an array with Item values from a file.
 * Receive: fileName, a char*,
 *          a, the address of a pointer to an Item array,
 *          n, the address of an int.
 * PRE: fileName contains N, followed by N double values.
 * POST: a points to a dynamically allocated array
 *        containing the N values from fileName
 *        and n == N.
 */

void readArray(char * fileName, Item** a, int * n) {
  int count, howMany;
  Item* tempA;
  FILE * fin;

  fin = fopen(fileName, "r");
  if (fin == NULL) {
    fprintf(stderr, "\n*** Unable to open input file '%s'\n\n",
                     fileName);
    exit(1);
  }

  fscanf(fin, "%d", &howMany);
  tempA = calloc(howMany, sizeof(Item));
  if (tempA == NULL) {
    fprintf(stderr, "\n*** Unable to allocate %d-length array",
                     howMany);
    exit(1);
  }

  for (count = 0; count < howMany; count++)
   fscanf(fin, "%lf", &tempA[count]);

  fclose(fin);

  *n = howMany;
  *a = tempA;
}

/* arraySquareAndSum sums the squares of the values
 *  in an array of numeric Items.
 * Receive: a, a pointer to the head of an array of Items;
 *          numValues, the number of values in the array.
 * Return: the sum of the values in the array.
 */

Item arraySquareAndSum(Item* a, int numValues) {
  Item result = 0.0;

  for (int i = 0; i < numValues; ++i) {
    result += (a[i] * a[i]);
  }

  return result;
}

]0;ajm94@remotel1: ~/CS374/Homework04/original[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/original[00m$ make
make: 'squareAndSum' is up to date.
]0;ajm94@remotel1: ~/CS374/Homework04/original[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/original[00m$ ./squareAndSum /home/cs/374/exercises/04/10m-doubles.txt 
The sum of the squares of the values in the file '/home/cs/374/exercises/04/10m-doubles.txt' is 3.33284e+06
Times: 2.238130, 0.025489, 2.263620
]0;ajm94@remotel1: ~/CS374/Homework04/original[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/original[00m$ cd ../
]0;ajm94@remotel1: ~/CS374/Homework04[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04[00m$ cd sequential\ binary/
]0;ajm94@remotel1: ~/CS374/Homework04/sequential binary[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/sequential binary[00m$ cat squareAndSum.c 
/* squareAndSum.c computes the sum of the squares
 *  of the values in an input file,
 *  whose name is given on the command-line.
 *
 * The program is written using typedef to declare
 *  Item as a generic type, currently double.
 *
 * Joel Adams, Fall 2023
 * for CS 374 (HPC) at Calvin University.
 * 
 * Alex Miller
 * Calvin University
 * 6 Dec 2023
 * 
 */

#include <stdio.h>      /* I/O */
#include <stdlib.h>     /* calloc(), exit(), etc. */
#include <mpi.h>

typedef double Item;

void readArray(char * fileName, Item ** a, int * n);
double arraySquareAndSum(Item* a, int numValues);

char* processCmdLineArgs(int argc, char** argv);
void check(FILE* fptr, char* fileName);
long getFileSize(FILE* fPtr);

int main(int argc, char * argv[])
{
  int numProcesses = -1;
  int id = -1;

  MPI_Init(&argc, &argv);
  MPI_Comm_rank(MPI_COMM_WORLD, &id);
  MPI_Comm_size(MPI_COMM_WORLD, &numProcesses);
  double start_time = MPI_Wtime();

  char* fileName = processCmdLineArgs(argc, argv);

  FILE* filePtr = fopen(fileName, "rb");
  check(filePtr, fileName);

  long numBytes = getFileSize(filePtr);
  long numItems = numBytes / sizeof(Item);
  Item* arrayPtr = (Item*) malloc( numItems * sizeof(Item) );

  fread(arrayPtr, sizeof(Item), numItems, filePtr);

  fclose(filePtr);

  double afterArrTime = MPI_Wtime() - start_time;
  double sum_start = MPI_Wtime();
  double sum = arraySquareAndSum(arrayPtr, numItems);

  double sumTime = MPI_Wtime() - sum_start;

  printf("The sum of the squares of the values in the file '%s' is %g\nTimes: %f, %f, %f\n", argv[1], sum, afterArrTime, sumTime, afterArrTime + sumTime);
  return 0;
}

/* arraySquareAndSum sums the squares of the values
 *  in an array of numeric Items.
 * Receive: a, a pointer to the head of an array of Items;
 *          numValues, the number of values in the array.
 * Return: the sum of the values in the array.
 */

Item arraySquareAndSum(Item* a, int numValues) {
  Item result = 0.0;

  for (int i = 0; i < numValues; ++i) {
    result += (a[i] * a[i]);
  }

  return result;
}

/* utility to check and process the command line argument
 * @param: argc, an int
 * @param: argv, a char**
 * Precondition: argc == 2
 *            && argv[1] is the name of the input file.
 * @return: argv[1].
 */
char* processCmdLineArgs(int argc, char** argv) {
   if (argc != 2) {
      fprintf(stderr, "\n\n*** Usage: ./seqTextOut N\n\n");
      exit(1);
   }

   return argv[1]; 
}

/* utility to check that opening the file succeeded.
 * @param: fPtr, a FILE*
 * @param: fileName, a char*
 * Precondition: fPtr holds the result of a call to fopen()
 *            && fileName is the name of the arg to fopen().
 * Postcondition: if fPtr == NULL, an error message has been displayed.
 */
void check(FILE* fPtr, char* fileName) {
   if (fPtr == NULL) {
      fprintf(stderr, "\n*** Unable to open file '%s'\n\n",
                                fileName);
   }
}

/* utility to calculate the size of an open file in bytes
 * @param: fPtr, a FILE*
 * Precondition: fPtr is to a file that has just been opened.
 * @return: the number of bytes in the file.
 */
long getFileSize(FILE* fPtr) {
    // seek to the end of the file.
    fseek(fPtr, 0L, SEEK_END);

    // calculate the size of the file
    long res = ftell(fPtr);

    // return the file ptr to the beginng
    fseek(fPtr, 0L, SEEK_SET);

    return res;
}

]0;ajm94@remotel1: ~/CS374/Homework04/sequential binary[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/sequential binary[00m$ make
make: 'squareAndSum' is up to date.
]0;ajm94@remotel1: ~/CS374/Homework04/sequential binary[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/sequential binary[00m$ makecat squareAndSum.c d sequential\ binary/../[K./squareAndSum /home/cs/374/exercises/04/10m-doubles.txt [K[K[K[Kbin 
The sum of the squares of the values in the file '/home/cs/374/exercises/04/10m-doubles.bin' is 3.33284e+06
Times: 0.164930, 0.025212, 0.190142
]0;ajm94@remotel1: ~/CS374/Homework04/sequential binary[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/sequential binary[00m$ ./squareAndSum /home/cs/374/exercises/04/10m-doubles.bin [C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Kcd ../parallel\ binary/
]0;ajm94@remotel1: ~/CS374/Homework04/parallel binary[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/parallel binary[00m$ cat parSquareSum.cpp 
/* squareAndSum.c computes the sum of the squares
 *  of the values in an input file,
 *  whose name is given on the command-line.
 *
 * The program is written using typedef to declare
 *  Item as a generic type, currently double.
 *
 * Joel Adams, Fall 2023
 * for CS 374 (HPC) at Calvin University.
 * Alex Miller 
 * Calvin University 
 * Nov 15, 2023
 * Homework 04
 */

#include <stdio.h> /* I/O */
#include <stdlib.h> /* calloc(), exit(), etc. */
#include <mpi.h>
#include <vector> 
#include "OO_MPI_IO.h" // ParallelReader


typedef double Item;

void readArray(char * fileName, Item ** a, int * n);
double vectorSquareAndSum(std::vector<double> val);
char* processCmdLineArgs(int argc, char** argv);
void check(FILE* fptr, char* fileName);
long getFileSize(FILE* fPtr);

int main(int argc, char * argv[])
{
  Item sum;
  Item totalSum;
  double startTime = 0.0;
  double readTime = 0.0;
  double totalTime = 0.0;
  double sumTime = 0.0;
  double sumStart = 0.0;
  const int MASTER = 0;
  int id = -1, numProcs = -1;

  MPI_Init(&argc, &argv);
  MPI_Comm_size(MPI_COMM_WORLD, &numProcs);
  MPI_Comm_rank(MPI_COMM_WORLD, &id);

  startTime = MPI_Wtime();

  char* fileName = processCmdLineArgs(argc, argv);

  ParallelReader<double> reader(fileName, MPI_DOUBLE, id, numProcs);
  std::vector<double> vec;
  reader.readChunk(vec);

  if (argc != 2) {
    fprintf(stderr, "\n*** Usage: squareAndSum <inputFile>\n\n");
    exit(1);
  }
  readTime = MPI_Wtime() - startTime;
  sumStart = MPI_Wtime();

  sum = vectorSquareAndSum(vec);


  sumTime = MPI_Wtime() - sumStart;
  totalTime = readTime + sumTime;

  MPI_Reduce(&sum, &totalSum, 1, MPI_DOUBLE, MPI_SUM, 0, MPI_COMM_WORLD);
  reader.close();

if(id == MASTER) {
  printf("\nThe sum of the squares of the values in the file '%s' is %g\n", argv[1], totalSum);
  printf("Read Time:\tSum Time:\tTotal Time:\n%f \t%f  \t%f\n", readTime, sumTime, totalTime);
}

  MPI_Finalize();
  return 0;
}

/* utility to check and process the command line argument
 * @param: argc, an int
 * @param: argv, a char**
 * Precondition: argc == 2
 *            && argv[1] is the name of the input file.
 * @return: argv[1].
 */
char* processCmdLineArgs(int argc, char** argv) {
   if (argc != 2) {
      fprintf(stderr, "\n\n*** Usage: ./seqTextOut N\n\n");
      exit(1);
   }

   return argv[1];
}


/* vectorSquareAndSum sums the squares of the values
 *  in an vector of numeric Items.
 * Receive: val, a pointer to the head of an vector of Items;
 * 
 * Return: the sum of the values in the vector.
 */
Item vectorSquareAndSum(std::vector<double> val) {
  Item result = 0.0;

  for (int i = 0; i < val.size(); i++) {
    result += (val[i] * val[i]);
  }

  return result;
}]0;ajm94@remotel1: ~/CS374/Homework04/parallel binary[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/parallel binary[00m$ make
make: 'parSquareSum' is up to date.
]0;ajm94@remotel1: ~/CS374/Homework04/parallel binary[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/parallel binary[00m$ mpirun -np 6 ./parSquareSum /home/cs/374/exercises/04/10m-doubles.bin 

The sum of the squares of the values in the file '/home/cs/374/exercises/04/10m-doubles.bin' is 3.33284e+06
Read Time:	Sum Time:	Total Time:
0.143052 	0.025385  	0.168437
]0;ajm94@remotel1: ~/CS374/Homework04/parallel binary[01;32majm94@remotel1[00m:[01;34m~/CS374/Homework04/parallel binary[00m$ exit

Script done on 2023-11-29 01:31:27-05:00 [COMMAND_EXIT_CODE="0"]
